language: r
cache: packages


branches:
  only:
  - master

env:
  global:
    - secure: "k0GJw2P5H5NEkVKV/jhSzSD/XIV5LOucDq8LCNjlSdVzFp6GcONXCIlKy1OE38q6FhgaUgdzNfgzydlfCfnSI8R04aDOpHzWx3qUqghkuzZlQjhkB5e8Dq/L4VLmQPAcbC0mOAC3oF6IjCzMsrst9xYtEitV9zY8cx4qJVDEkxx9HyEuyDCDbmSeN/PY3p4w3mKEjChcG7jYpS+8elNUuTHwdC5OCtnjA5v0Ni9kN0qEI+u2BUa2Tqym/7E2pdfe/HyqKgSr4+E6cg1feH+eJI1PKWCvv8sBmbgZpxRNzT9vvrbgm2fdSyskrMej26TEG2Sw0K4kCBmwnCr2oemJLkfSeXwz5phxbUhhxGMAzL8dEGjsIx5MEfbmtrHNSNV77S6hUcUymi6Ig4d6sQ+MQGv4VGRmJH6zP+tPnVPle+WmPm2p+NJP+2cUxDeS+/QXH4vSBRWWyLhVcvCfFs02J20kRjANBkoUxhwoHDZs9tvjB8QtMm+MDwcf1iXP5uwRoJVm1IeHjvw5dubn6HlVn+WAH7HtNj2LS43AzXasq+Y8hdRR6OFMwvEVXtj6HZNUPoaCFmjKICkasgVRvQ+dSZiBs/wHkaHTBP3lNzE3t5xZzPpbBCsR4c/QH1SN0dv7LtkQz6uUplhO1b84zZWmdbuyZibhWBrQZAjUr09vxWk="

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
